// Auto-generated from docs/list.txt - do not edit manually
// Total: 683 seed rules across 19 categories

import type { FilterRuleSeed } from '../../types/FilterRule';

export const seedRules: FilterRuleSeed[] = [
  // Antioxidationsmittel (10)
  {
    key: 'Antioxidant',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'BHA',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'BHT',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Ascorbate',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Octyl Gallate',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Propyl Gallate',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Ascorbate',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Erythorbate',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'TBHQ',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Tocopherols',
    category: 'Antioxidationsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // E-Nummern (243)
  {
    key: 'E102',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E104',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E110',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E1103',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E1105',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E122',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E123',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E124',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E127',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E129',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E131',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E132',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E133',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E140',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E1400',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E141',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E1451',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E150a',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E150b',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E150c',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E150d',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E151',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E153',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E155',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E160b',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E160c',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E160d',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E161b',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E161g',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E162',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E163',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E170',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E171',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E172',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E173',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E174',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E175',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E180',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E202',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E210',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E211',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E212',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E213',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E218',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E220',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E221',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E222',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E223',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E224',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E225',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E226',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E227',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E228',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E234',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E235',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E239',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E242',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E243',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E249',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E250',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E251',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E260',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E262',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E263',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E264',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E270',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E280',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E282',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E284',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E285',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E290',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E296',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E297',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E301',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E302',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E303',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E304',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E306',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E307',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E308',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E309',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E310',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E311',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E312',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E315',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E316',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E319',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E320',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E321',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E322',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E325',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E326',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E327',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E330',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E331',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E332',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E333',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E334',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E335',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E336',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E338',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E339',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E340',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E341',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E342',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E343',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E350',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E351',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E352',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E353',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E354',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E355',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E356',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E357',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E363',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E385',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E392',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E406',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E407',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E407a',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E410',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E412',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E413',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E414',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E415',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E416',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E417',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E418',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E420',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E421',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E423',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E425',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E427',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E432',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E433',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E434',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E435',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E440',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E450',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E451',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E452',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E459',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E471',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E472a',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E472b',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E472c',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E473',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E474',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E475',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E477',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E481',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E482',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E491',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E500',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E501',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E503',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E504',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E507',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E512',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E513',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E514',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E515',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E516',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E517',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E520',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E521',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E522',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E523',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E524',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E525',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E526',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E527',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E528',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E529',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E530',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E535',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E536',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E538',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E541',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E551',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E552',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E553a',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E553b',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E554',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E555',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E556',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E558',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E559',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E570',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E574',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E575',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E576',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E577',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E578',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E579',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E585',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E586',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E620',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E621',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E622',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E623',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E624',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E625',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E626',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E627',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E628',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E629',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E630',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E631',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E632',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E633',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E634',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E635',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E640',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E641',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E650',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E900',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E901',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E902',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E903',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E904',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E938',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E939',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E941',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E942',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E948',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E949',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E950',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E951',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E953',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E954',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E955',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E957',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E959',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E960',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E961',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E962',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E964',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E965',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E966',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E967',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E968',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'E969',
    category: 'E-Nummern',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Emulgatoren & Stabilisatoren (19)
  {
    key: 'Aluminium Stearate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Stearate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Stearoyl Fumarate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Stearoyl Lactylate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Emulsifier',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Fatty Acids',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Lecithin',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Stearate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Mono Diglycerides',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Polyglycerol Esters',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Stearate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Propane Diol Esters',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Caseinate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Stearate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Stearoyl Fumarate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Stearoyl Lactylate',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Stabiliser',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sucroglycerides',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sucrose Esters',
    category: 'Emulgatoren & Stabilisatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Farbstoffe (32)
  {
    key: 'Allura Red',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Allura Red AC',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Amaranth',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Annatto',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Artificial Colors',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Azorubine',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Blue 1',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Blue 2',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Brown HT',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Canthaxanthin',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Caramel',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Caramel Color',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Carbon Black',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Chlorophyll',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Color',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Copper Chlorophyll',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Erythrosine',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Green 3',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Indigotine',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Iron Oxides',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Litholrubine BK',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Lycopene',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Paprika Extract',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Patent Blue',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ponceau 4R',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Quinoline Yellow',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Red 40',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sunset Yellow',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Tartrazin',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Titanium Dioxide',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Yellow 5',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Yellow 6',
    category: 'Farbstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Füll- & Trägerstoffe (14)
  {
    key: 'Anti Caking Agent',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Anti Foaming Agent',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Bentonite',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Bulking Agent',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Carrier Solvent',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Dimethylpolysiloxane',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Firming Agent',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Foaming Agent',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glycerol',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Humectant',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Kaolin',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Packaging Gas',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Propellants',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Talc',
    category: 'Füll- & Trägerstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Gehärtete Fette & raffinierte Öle (39)
  {
    key: 'Cocoa Butter Substitute',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Cottonseed Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Fat Replacer',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Grapeseed Oil Refined',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hardened Coconut Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hardened Palm Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hardened Vegetable Fat',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrogenated Coconut Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrogenated Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrogenated Palm Kernel Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrogenated Palm Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrogenated Soybean Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrogenated Sunflower Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrogenated Vegetable Fat',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Interesterified Fat',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Interesterified Vegetable Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Margarine',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Palm Fat',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Palm Kernel Fat',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Palm Kernel Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Palm Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Palm Oil Refined',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Palm Stearin',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Partially Hydrogenated Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Partially Hydrogenated Soybean Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Partially Hydrogenated Vegetable Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Plant Fat Hardened',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Plant Fat Refined',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Plant Margarine',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Rapeseed Oil Refined',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Refined Coconut Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Refined Corn Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Refined Sunflower Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Refined Vegetable Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Soybean Oil',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Soybean Oil Refined',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sunflower Oil Refined',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Trans Fat',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Waffle Fat Hardened',
    category: 'Gehärtete Fette & raffinierte Öle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Geschmacksverstärker & Aromen (36)
  {
    key: 'Artificial Beef Flavor',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Artificial Butter Flavor',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Artificial Chicken Flavor',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Artificial Flavors',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Autolyzed Yeast',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Autolyzed Yeast Extract',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Diglutamate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Guanylate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Inosinate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Dipotassium Guanylate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Dipotassium Inosinate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Disodium 5 Ribonucleotides',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Disodium Guanylate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Disodium Inosinate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Flavor Enhancer',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrolyzed Corn Protein',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrolyzed Plant Protein',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrolyzed Protein',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrolyzed Soy Protein',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrolyzed Vegetable Protein',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrolyzed Wheat Protein',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'MSG',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Diglutamate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Monoammonium Glutamate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Monopotassium Glutamate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Monosodium Glutamate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Natural Flavor Enhancer',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Natural Flavors',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Guanylate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Inosinate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Guanylate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Inosinate',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Synthetic Vanillin',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Vanilla Flavor Artificial',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Vanilla Powder Artificial',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Yeast Extract',
    category: 'Geschmacksverstärker & Aromen',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Konservierungsstoffe (27)
  {
    key: 'Borax',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Boric Acid',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Benzoate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Disodium EDTA',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Propionate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Dimethyl Dicarbonate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'EDTA',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ethyl Lauroyl Arginate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hexamethylene Tetramine',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Methylparaben',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Natamycin',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Nisin',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Polysorbate 20',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Polysorbate 40',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Polysorbate 60',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Polysorbate 80',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Benzoate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Nitrate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Nitrite',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Sorbate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Propylparaben',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Benzoate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Metabisulphite',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Nitrate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Nitrite',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Propionate',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Sulphite',
    category: 'Konservierungsstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Metalle (3)
  {
    key: 'Aluminium',
    category: 'Metalle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  { key: 'Gold', category: 'Metalle', type: 'ingredient' as const, severity: 'red_flag' as const },
  {
    key: 'Silver',
    category: 'Metalle',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Modifizierte Stärken (32)
  {
    key: 'Acetylated Distarch Adipate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Acetylated Distarch Phosphate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Acetylated Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Beta Cyclodextrin',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Bleached Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Corn Maltodextrin',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Corn Starch Modified',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Cross Linked Starches',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Dextrin',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Distarch Glycerol',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Distarch Phosphate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Enzyme Treated Starches',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Flour Treatment Agent',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydroxypropyl Distarch Glycerol',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydroxypropyl Distarch Phosphate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydroxypropyl Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Maize Starch Modified',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Maltodextrin',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Modified Corn Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Modified Potato Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Modified Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Modified Wheat Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Monostarch Phosphate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Octenyl Succinic Acid Modified Gum Arabic',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Oxidized Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Phosphated Distarch Phosphate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Roasted Starch',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Starch Acetate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Starch Sodium Octenyl Succinate',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Wheat Starch Modified',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'White Dextrin',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Yellow Dextrin',
    category: 'Modifizierte Stärken',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Phosphate & Mineralstoffe (76)
  {
    key: 'Aluminium Ammonium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Aluminium Potassium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Aluminium Sodium Silicate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Aluminium Sodium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Aluminium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Bicarbonate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Carbonates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Hydroxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Lactate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Phosphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Aluminium Silicate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Aluminium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Carbonate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Citrate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Ferrocyanide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Hydroxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Lactate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Oxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Phosphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Polyphosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Silicate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Tartrate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Carbon Dioxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Dicalcium Phosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ferrous Lactate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Carbonates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Hydroxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Lactate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Oxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Phosphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Magnesium Silicate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Monocalcium Phosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Nitrous Oxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Polyphosphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Aluminium Silicate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Aluminium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Bicarbonate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Bromate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Carbonates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Citrate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Ferrocyanide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Hexametaphosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Hydroxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Lactate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Malates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Metaphosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Phosphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Sulphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Tartrate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Tripolyphosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Silicon Dioxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Aluminium Phosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Aluminium Phosphate Acidic',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Aluminium Phosphate Basic',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Aluminium Silicate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Bicarbonate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Carbonates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Citrate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Ferrocyanide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Hexametaphosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Hydroxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Lactate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Malates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Metaphosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Phosphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Pyrophosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Sulphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Tartrate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Tripolyphosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Stannous Chloride',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sulphur Dioxide',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Tetrasodium Pyrophosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Tricalcium Phosphate',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Triphosphates',
    category: 'Phosphate & Mineralstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Proteine & Fleischersatz (16)
  {
    key: 'Casein',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Casein Hydrolysate',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Defatted Soy Flour',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Mechanically Recovered Meat',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Mechanically Separated Meat',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Mechanically Separated Poultry',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Skim Milk Powder',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Soy Flour Defatted',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Soy Protein',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Soy Protein Concentrate',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Soy Protein Isolate',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Textured Soy Protein',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Textured Vegetable Protein',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Whey Powder',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Whey Protein Concentrate',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Whey Protein Isolate',
    category: 'Proteine & Fleischersatz',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Sonstige Zusatzstoffe (10)
  {
    key: 'Azodicarbonamide',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'BPA',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Extracts of Rosemary',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Gelatin',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glycine',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'L Leucine',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Lysozyme',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Perfluoroalkyl Chemicals',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Phthalates',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Table Salt Iodized',
    category: 'Sonstige Zusatzstoffe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Säuren & Säureregulatoren (38)
  {
    key: 'Acidity Regulator',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Adipic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Acetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ammonium Diacetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Acetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Adipate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Diacetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Gluconate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Calcium Malate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Citric Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Ferrous Gluconate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Fumaric Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Gluconic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glucono Delta Lactone',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glutamic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Hydrochloric Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Inosinic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Lactic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Lactic Acid Esters',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Malic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Metatartaric Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Phosphoric Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Acetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Adipate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Diacetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Gluconate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Potassium Malate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Propionic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Acetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Acid Pyrophosphate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Adipate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Diacetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Gluconate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sodium Malate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Succinic Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sulphuric Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Tartaric Acid',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Zinc Acetate',
    category: 'Säuren & Säureregulatoren',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Süßungsmittel (35)
  {
    key: 'Acesulfame K',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Acesulfame Potassium',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Advantame',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Artificial Sweeteners',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Aspartame',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Erythritol',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Grape Sugar Syrup',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Industrial Sugar',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Invert Sugar',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Invert Sugar Syrup',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Isomalt',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Lactitol',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Maltitol',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Mannitol',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Neohesperidine DC',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Neotame',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Polyglycitol Syrup',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Raw Cane Sugar',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Refined Sugar',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Saccharin',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Saccharin Sodium',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Salt of Aspartame Acesulfame',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sorbitol',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Steviol Glycosides',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sucralose',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sugar',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sugar Beet Syrup',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sugar Cane Syrup',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sugar Color',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sugar Syrup',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sweet Whey Powder',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sweetener',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Thaumatin',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'White Sugar',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Xylitol',
    category: 'Süßungsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Treib- & Schutzgase (3)
  {
    key: 'Helium',
    category: 'Treib- & Schutzgase',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Nitrogen',
    category: 'Treib- & Schutzgase',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Oxygen',
    category: 'Treib- & Schutzgase',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Trenn- & Überzugsmittel (4)
  {
    key: 'Beeswax',
    category: 'Trenn- & Überzugsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Candelilla Wax',
    category: 'Trenn- & Überzugsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Carnauba Wax',
    category: 'Trenn- & Überzugsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Shellac',
    category: 'Trenn- & Überzugsmittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Verdickungs- & Geliermittel (16)
  {
    key: 'Acacia Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'British Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Carrageenan',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Cassia Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Gellan Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Gelling Agent',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Guar Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Karaya Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Konjac',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Locust Bean Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Pectins',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Processed Eucheuma Seaweed',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Tara Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Thickener',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Tragacanth',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Xanthan Gum',
    category: 'Verdickungs- & Geliermittel',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  // Zucker & Sirupe (30)
  {
    key: 'Agave Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Brown Rice Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Corn Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Corn Syrup Solids',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Dextrose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Evaporated Cane Juice',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Fructose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Fructose Corn Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Fructose Glucose Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glucose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glucose Fructose Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glucose Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Glucose Syrup Solids',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'HFCS',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'High Fructose Corn Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Invertase',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Isoglucose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Lactose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Malt Extract',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Malt Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Maltose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Maltose Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Molasses',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Oat Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Pear Syrup Concentrate',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Rice Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Saccharose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Sucrose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Wheat Glucose Syrup',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
  {
    key: 'Wheat Maltose',
    category: 'Zucker & Sirupe',
    type: 'ingredient' as const,
    severity: 'red_flag' as const,
  },
];
