import type { AdditiveInfo } from './AdditiveTaxonomyTypes';

export const ADDITIVE_TAXONOMY: AdditiveInfo[] = [
  // ===== Farbstoffe (Colours) E100-E199 =====
  {
    eNumber: 'E100',
    name: 'Kurkumin',
    functionClass: 'Farbstoff',
    riskLevel: 'none',
    aliases: ['Kurkumin', 'Curcumin', 'E 100'],
  },
  {
    eNumber: 'E101',
    name: 'Riboflavin',
    functionClass: 'Farbstoff',
    riskLevel: 'none',
    aliases: ['Riboflavin', 'Vitamin B2', 'E 101'],
  },
  {
    eNumber: 'E102',
    name: 'Tartrazin',
    functionClass: 'Farbstoff',
    riskLevel: 'high',
    aliases: ['Tartrazin', 'Tartrazine', 'E 102'],
  },
  {
    eNumber: 'E104',
    name: 'Chinolingelb',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Chinolingelb', 'E 104'],
  },
  {
    eNumber: 'E110',
    name: 'Gelborange S',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Gelborange S', 'Sunsetgelb', 'Sunset Yellow', 'E 110'],
  },
  {
    eNumber: 'E120',
    name: 'Karmin',
    functionClass: 'Farbstoff',
    riskLevel: 'low',
    aliases: ['Karmin', 'Carmine', 'Cochenille', 'E 120'],
  },
  {
    eNumber: 'E122',
    name: 'Azorubin',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Azorubin', 'Carmoisin', 'E 122'],
  },
  {
    eNumber: 'E123',
    name: 'Amaranth',
    functionClass: 'Farbstoff',
    riskLevel: 'high',
    aliases: ['Amaranth', 'E 123'],
  },
  {
    eNumber: 'E124',
    name: 'Cochenillerot A',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Cochenillerot A', 'Ponceau 4R', 'E 124'],
  },
  {
    eNumber: 'E127',
    name: 'Erythrosin',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Erythrosin', 'E 127'],
  },
  {
    eNumber: 'E129',
    name: 'Allurarot AC',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Allurarot', 'Allura Red', 'E 129'],
  },
  {
    eNumber: 'E131',
    name: 'Patentblau V',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Patentblau V', 'Patent Blue V', 'E 131'],
  },
  {
    eNumber: 'E132',
    name: 'Indigotin',
    functionClass: 'Farbstoff',
    riskLevel: 'low',
    aliases: ['Indigotin', 'Indigokarmin', 'E 132'],
  },
  {
    eNumber: 'E133',
    name: 'Brillantblau FCF',
    functionClass: 'Farbstoff',
    riskLevel: 'low',
    aliases: ['Brillantblau', 'Brilliant Blue', 'E 133'],
  },
  {
    eNumber: 'E141',
    name: 'Kupferhaltige Chlorophylle',
    functionClass: 'Farbstoff',
    riskLevel: 'low',
    aliases: ['Kupfer-Chlorophyll', 'E 141'],
  },
  {
    eNumber: 'E142',
    name: 'Grün S',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Grün S', 'Green S', 'E 142'],
  },
  {
    eNumber: 'E150a',
    name: 'Zuckerkulör',
    functionClass: 'Farbstoff',
    riskLevel: 'none',
    aliases: ['Zuckerkulör', 'Karamell', 'E 150a'],
  },
  {
    eNumber: 'E150c',
    name: 'Ammoniak-Zuckerkulör',
    functionClass: 'Farbstoff',
    riskLevel: 'low',
    aliases: ['Ammoniak-Zuckerkulör', 'E 150c'],
  },
  {
    eNumber: 'E150d',
    name: 'Ammoniumsulfit-Zuckerkulör',
    functionClass: 'Farbstoff',
    riskLevel: 'low',
    aliases: ['Ammoniumsulfit-Zuckerkulör', 'E 150d'],
  },
  {
    eNumber: 'E151',
    name: 'Brillantschwarz BN',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Brillantschwarz', 'Black PN', 'E 151'],
  },
  {
    eNumber: 'E153',
    name: 'Pflanzenkohle',
    functionClass: 'Farbstoff',
    riskLevel: 'low',
    aliases: ['Pflanzenkohle', 'Aktivkohle', 'E 153'],
  },
  {
    eNumber: 'E155',
    name: 'Braun HT',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Braun HT', 'Brown HT', 'E 155'],
  },
  {
    eNumber: 'E160a',
    name: 'Beta-Carotin',
    functionClass: 'Farbstoff',
    riskLevel: 'none',
    aliases: ['Beta-Carotin', 'Carotin', 'β-Carotin', 'E 160a'],
  },
  {
    eNumber: 'E160c',
    name: 'Paprikaextrakt',
    functionClass: 'Farbstoff',
    riskLevel: 'none',
    aliases: ['Paprikaextrakt', 'Capsanthin', 'E 160c'],
  },
  {
    eNumber: 'E162',
    name: 'Betenrot',
    functionClass: 'Farbstoff',
    riskLevel: 'none',
    aliases: ['Betenrot', 'Betenfarbstoff', 'E 162'],
  },
  {
    eNumber: 'E163',
    name: 'Anthocyane',
    functionClass: 'Farbstoff',
    riskLevel: 'none',
    aliases: ['Anthocyane', 'Anthocyanine', 'E 163'],
  },
  {
    eNumber: 'E171',
    name: 'Titandioxid',
    functionClass: 'Farbstoff',
    riskLevel: 'high',
    aliases: ['Titandioxid', 'Titanium Dioxide', 'E 171'],
  },
  {
    eNumber: 'E173',
    name: 'Aluminium',
    functionClass: 'Farbstoff',
    riskLevel: 'medium',
    aliases: ['Aluminium', 'Aluminum', 'E 173'],
  },

  // ===== Konservierungsstoffe (Preservatives) E200-E299 =====
  {
    eNumber: 'E200',
    name: 'Sorbinsäure',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'low',
    aliases: ['Sorbinsäure', 'E 200'],
  },
  {
    eNumber: 'E202',
    name: 'Kaliumsorbat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'low',
    aliases: ['Kaliumsorbat', 'E 202'],
  },
  {
    eNumber: 'E210',
    name: 'Benzoesäure',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'medium',
    aliases: ['Benzoesäure', 'E 210'],
  },
  {
    eNumber: 'E211',
    name: 'Natriumbenzoat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'medium',
    aliases: ['Natriumbenzoat', 'E 211'],
  },
  {
    eNumber: 'E212',
    name: 'Kaliumbenzoat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'medium',
    aliases: ['Kaliumbenzoat', 'E 212'],
  },
  {
    eNumber: 'E220',
    name: 'Schwefeldioxid',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Schwefeldioxid', 'Sulphur Dioxide', 'E 220'],
  },
  {
    eNumber: 'E221',
    name: 'Natriumsulfit',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Natriumsulfit', 'E 221'],
  },
  {
    eNumber: 'E222',
    name: 'Natriumhydrogensulfit',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Natriumhydrogensulfit', 'E 222'],
  },
  {
    eNumber: 'E223',
    name: 'Natriummetabisulfit',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Natriummetabisulfit', 'E 223'],
  },
  {
    eNumber: 'E224',
    name: 'Kaliummetabisulfit',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Kaliummetabisulfit', 'E 224'],
  },
  {
    eNumber: 'E228',
    name: 'Kaliumhydrogensulfit',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Kaliumhydrogensulfit', 'E 228'],
  },
  {
    eNumber: 'E235',
    name: 'Natamycin',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'low',
    aliases: ['Natamycin', 'Pimaricin', 'E 235'],
  },
  {
    eNumber: 'E242',
    name: 'Dimethyldicarbonat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'low',
    aliases: ['Dimethyldicarbonat', 'DMDC', 'E 242'],
  },
  {
    eNumber: 'E249',
    name: 'Kaliumnitrit',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Kaliumnitrit', 'E 249'],
  },
  {
    eNumber: 'E250',
    name: 'Natriumnitrit',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Natriumnitrit', 'E 250'],
  },
  {
    eNumber: 'E251',
    name: 'Natriumnitrat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Natriumnitrat', 'E 251'],
  },
  {
    eNumber: 'E252',
    name: 'Kaliumnitrat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Kaliumnitrat', 'E 252'],
  },
  {
    eNumber: 'E260',
    name: 'Essigsäure',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'none',
    aliases: ['Essigsäure', 'E 260'],
  },
  {
    eNumber: 'E270',
    name: 'Milchsäure',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'none',
    aliases: ['Milchsäure', 'Lactic Acid', 'E 270'],
  },
  {
    eNumber: 'E280',
    name: 'Propionsäure',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'low',
    aliases: ['Propionsäure', 'E 280'],
  },
  {
    eNumber: 'E281',
    name: 'Natriumpropionat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'low',
    aliases: ['Natriumpropionat', 'E 281'],
  },
  {
    eNumber: 'E282',
    name: 'Calciumpropionat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'low',
    aliases: ['Calciumpropionat', 'E 282'],
  },
  {
    eNumber: 'E285',
    name: 'Natriumtetraborat',
    functionClass: 'Konservierungsstoff',
    riskLevel: 'high',
    aliases: ['Natriumtetraborat', 'Borax', 'E 285'],
  },

  // ===== Antioxidationsmittel (Antioxidants) E300-E399 =====
  {
    eNumber: 'E300',
    name: 'Ascorbinsäure',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'none',
    aliases: ['Ascorbinsäure', 'Vitamin C', 'E 300'],
  },
  {
    eNumber: 'E301',
    name: 'Natriumascorbat',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'none',
    aliases: ['Natriumascorbat', 'E 301'],
  },
  {
    eNumber: 'E304',
    name: 'Ascorbylpalmitat',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'low',
    aliases: ['Ascorbylpalmitat', 'E 304'],
  },
  {
    eNumber: 'E306',
    name: 'Tocopherolhaltige Extrakte',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'none',
    aliases: ['Tocopherol', 'Tocopherole', 'Vitamin E', 'E 306'],
  },
  {
    eNumber: 'E307',
    name: 'Alpha-Tocopherol',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'none',
    aliases: ['Alpha-Tocopherol', 'E 307'],
  },
  {
    eNumber: 'E310',
    name: 'Propylgallat',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'medium',
    aliases: ['Propylgallat', 'E 310'],
  },
  {
    eNumber: 'E319',
    name: 'tert-Butylhydrochinon',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'medium',
    aliases: ['TBHQ', 'tert-Butylhydrochinon', 'E 319'],
  },
  {
    eNumber: 'E320',
    name: 'Butylhydroxyanisol',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'medium',
    aliases: ['BHA', 'Butylhydroxyanisol', 'E 320'],
  },
  {
    eNumber: 'E321',
    name: 'Butylhydroxytoluol',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'medium',
    aliases: ['BHT', 'Butylhydroxytoluol', 'E 321'],
  },
  {
    eNumber: 'E322',
    name: 'Lecithin',
    functionClass: 'Emulgator',
    riskLevel: 'none',
    aliases: ['Lecithin', 'Lecithine', 'Sojalecithin', 'E 322'],
  },
  {
    eNumber: 'E325',
    name: 'Natriumlactat',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'none',
    aliases: ['Natriumlactat', 'E 325'],
  },
  {
    eNumber: 'E326',
    name: 'Kaliumlactat',
    functionClass: 'Antioxidationsmittel',
    riskLevel: 'none',
    aliases: ['Kaliumlactat', 'E 326'],
  },
  {
    eNumber: 'E330',
    name: 'Citronensäure',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'none',
    aliases: ['Citronensäure', 'Zitronensäure', 'E 330'],
  },
  {
    eNumber: 'E331',
    name: 'Natriumcitrate',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'none',
    aliases: ['Natriumcitrat', 'Natriumcitrate', 'E 331'],
  },
  {
    eNumber: 'E334',
    name: 'Weinsäure',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'none',
    aliases: ['Weinsäure', 'E 334'],
  },
  {
    eNumber: 'E338',
    name: 'Phosphorsäure',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'medium',
    aliases: ['Phosphorsäure', 'E 338'],
  },
  {
    eNumber: 'E339',
    name: 'Natriumphosphate',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'low',
    aliases: ['Natriumphosphat', 'Natriumphosphate', 'E 339'],
  },
  {
    eNumber: 'E340',
    name: 'Kaliumphosphate',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'low',
    aliases: ['Kaliumphosphat', 'E 340'],
  },
  {
    eNumber: 'E350',
    name: 'Natriummalate',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'none',
    aliases: ['Natriummalat', 'E 350'],
  },
  {
    eNumber: 'E352',
    name: 'Calciummalate',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'none',
    aliases: ['Calciummalat', 'E 352'],
  },
  {
    eNumber: 'E363',
    name: 'Bernsteinsäure',
    functionClass: 'Säuerungsmittel',
    riskLevel: 'low',
    aliases: ['Bernsteinsäure', 'E 363'],
  },

  // ===== Emulgatoren und Verdickungsmittel E400-E499 =====
  {
    eNumber: 'E400',
    name: 'Alginsäure',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Alginsäure', 'E 400'],
  },
  {
    eNumber: 'E401',
    name: 'Natriumalginat',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Natriumalginat', 'E 401'],
  },
  {
    eNumber: 'E402',
    name: 'Kaliumalginat',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Kaliumalginat', 'E 402'],
  },
  {
    eNumber: 'E406',
    name: 'Agar-Agar',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Agar-Agar', 'Agar', 'E 406'],
  },
  {
    eNumber: 'E407',
    name: 'Carrageen',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'medium',
    aliases: ['Carrageen', 'Carrageenan', 'Carrageenan', 'E 407'],
  },
  {
    eNumber: 'E407a',
    name: 'Verarbeitete Eucheuma-Algen',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Eucheuma', 'E 407a'],
  },
  {
    eNumber: 'E410',
    name: 'Johannisbrotkernmehl',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Johannisbrotkernmehl', 'Carob', 'E 410'],
  },
  {
    eNumber: 'E412',
    name: 'Guarkernmehl',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Guarkernmehl', 'Guar', 'E 412'],
  },
  {
    eNumber: 'E414',
    name: 'Gummi arabicum',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Gummi arabicum', 'Akaziengummi', 'E 414'],
  },
  {
    eNumber: 'E415',
    name: 'Xanthan',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Xanthan', 'Xanthan Gum', 'E 415'],
  },
  {
    eNumber: 'E418',
    name: 'Gellangummi',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Gellangummi', 'Gellan', 'E 418'],
  },
  {
    eNumber: 'E420',
    name: 'Sorbit',
    functionClass: 'Süßungsmittel',
    riskLevel: 'low',
    aliases: ['Sorbit', 'Sorbitol', 'E 420'],
  },
  {
    eNumber: 'E421',
    name: 'Mannit',
    functionClass: 'Süßungsmittel',
    riskLevel: 'low',
    aliases: ['Mannit', 'Mannitol', 'E 421'],
  },
  {
    eNumber: 'E422',
    name: 'Glycerin',
    functionClass: 'Feuchthaltemittel',
    riskLevel: 'none',
    aliases: ['Glycerin', 'Glycerol', 'E 422'],
  },
  {
    eNumber: 'E425',
    name: 'Konjak',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Konjak', 'Konjac', 'E 425'],
  },
  {
    eNumber: 'E428',
    name: 'Gelatine',
    functionClass: 'Gelier- und Bindemittel',
    riskLevel: 'none',
    aliases: ['Gelatine', 'E 428'],
  },
  {
    eNumber: 'E432',
    name: 'Polysorbat 20',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Polysorbat 20', 'Tween 20', 'E 432'],
  },
  {
    eNumber: 'E433',
    name: 'Polysorbat 80',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Polysorbat 80', 'Tween 80', 'E 433'],
  },
  {
    eNumber: 'E435',
    name: 'Polysorbat 60',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Polysorbat 60', 'Tween 60', 'E 435'],
  },
  {
    eNumber: 'E440',
    name: 'Pektin',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Pektin', 'Pektine', 'E 440'],
  },
  {
    eNumber: 'E441',
    name: 'Gelatine',
    functionClass: 'Gelier- und Bindemittel',
    riskLevel: 'none',
    aliases: ['Gelatine', 'E 441'],
  },
  {
    eNumber: 'E450',
    name: 'Diphosphate',
    functionClass: 'Stabilisator',
    riskLevel: 'low',
    aliases: ['Diphosphat', 'Diphosphate', 'E 450'],
  },
  {
    eNumber: 'E451',
    name: 'Triphosphate',
    functionClass: 'Stabilisator',
    riskLevel: 'medium',
    aliases: ['Triphosphat', 'Triphosphate', 'E 451'],
  },
  {
    eNumber: 'E452',
    name: 'Polyphosphate',
    functionClass: 'Stabilisator',
    riskLevel: 'medium',
    aliases: ['Polyphosphat', 'Polyphosphate', 'E 452'],
  },
  {
    eNumber: 'E460',
    name: 'Cellulose',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'none',
    aliases: ['Cellulose', 'Zellulose', 'E 460'],
  },
  {
    eNumber: 'E461',
    name: 'Methylcellulose',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Methylcellulose', 'E 461'],
  },
  {
    eNumber: 'E464',
    name: 'Hydroxypropylmethylcellulose',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Hydroxypropylmethylcellulose', 'HPMC', 'E 464'],
  },
  {
    eNumber: 'E466',
    name: 'Carboxymethylcellulose',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Carboxymethylcellulose', 'CMC', 'E 466'],
  },
  {
    eNumber: 'E468',
    name: 'Vernetzte Carboxymethylcellulose',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['E 468'],
  },
  {
    eNumber: 'E471',
    name: 'Mono- und Diglyceride',
    functionClass: 'Emulgator',
    riskLevel: 'none',
    aliases: ['Mono- und Diglyceride', 'Monoglyceride', 'Diglyceride', 'E 471'],
  },
  {
    eNumber: 'E472a',
    name: 'Essigsäureester von MDG',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Essigsäureester', 'E 472a'],
  },
  {
    eNumber: 'E472b',
    name: 'Milchsäureester von MDG',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Milchsäureester', 'E 472b'],
  },
  {
    eNumber: 'E472e',
    name: 'Diacetylweinsäureester',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['DATEM', 'Diacetylweinsäureester', 'E 472e'],
  },
  {
    eNumber: 'E473',
    name: 'Zuckerester',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Zuckerester', 'E 473'],
  },
  {
    eNumber: 'E474',
    name: 'Zuckerglyceride',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Zuckerglyceride', 'E 474'],
  },
  {
    eNumber: 'E475',
    name: 'Polyglycerinester',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Polyglycerinester', 'E 475'],
  },
  {
    eNumber: 'E476',
    name: 'Polyglycerin-Polyricinoleat',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Polyglycerin-Polyricinoleat', 'PGPR', 'E 476'],
  },
  {
    eNumber: 'E481',
    name: 'Natriumstearoyl-2-lactylat',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Natriumstearoyl-2-lactylat', 'E 481'],
  },
  {
    eNumber: 'E491',
    name: 'Sorbitanmonostearat',
    functionClass: 'Emulgator',
    riskLevel: 'low',
    aliases: ['Sorbitanmonostearat', 'E 491'],
  },

  // ===== Geschmacksverstärker (Flavor enhancers) E620-E650 =====
  {
    eNumber: 'E620',
    name: 'Glutaminsäure',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'low',
    aliases: ['Glutaminsäure', 'E 620'],
  },
  {
    eNumber: 'E621',
    name: 'Mononatriumglutamat',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'medium',
    aliases: ['Mononatriumglutamat', 'MSG', 'Glutamat', 'E 621'],
  },
  {
    eNumber: 'E622',
    name: 'Monokaliumglutamat',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'medium',
    aliases: ['Monokaliumglutamat', 'E 622'],
  },
  {
    eNumber: 'E623',
    name: 'Calciumdiglutamat',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'medium',
    aliases: ['Calciumdiglutamat', 'E 623'],
  },
  {
    eNumber: 'E624',
    name: 'Monoammoniumglutamat',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'medium',
    aliases: ['Monoammoniumglutamat', 'E 624'],
  },
  {
    eNumber: 'E625',
    name: 'Magnesiumdiglutamat',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'medium',
    aliases: ['Magnesiumdiglutamat', 'E 625'],
  },
  {
    eNumber: 'E627',
    name: 'Dinatriumguanylat',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'low',
    aliases: ['Dinatriumguanylat', 'E 627'],
  },
  {
    eNumber: 'E631',
    name: 'Dinatriumosinat',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'low',
    aliases: ['Dinatriumosinat', 'E 631'],
  },
  {
    eNumber: 'E635',
    name: "Dinatrium-5'-ribonucleotid",
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'low',
    aliases: ['Dinatriumribonucleotid', 'E 635'],
  },

  // ===== Süßungsmittel (Sweeteners) E950-E969 =====
  {
    eNumber: 'E950',
    name: 'Acesulfam K',
    functionClass: 'Süßungsmittel',
    riskLevel: 'medium',
    aliases: ['Acesulfam', 'Acesulfam K', 'Acesulfam-K', 'E 950'],
  },
  {
    eNumber: 'E951',
    name: 'Aspartam',
    functionClass: 'Süßungsmittel',
    riskLevel: 'medium',
    aliases: ['Aspartam', 'E 951'],
  },
  {
    eNumber: 'E952',
    name: 'Cyclamat',
    functionClass: 'Süßungsmittel',
    riskLevel: 'medium',
    aliases: ['Cyclamat', 'E 952'],
  },
  {
    eNumber: 'E953',
    name: 'Isomalt',
    functionClass: 'Süßungsmittel',
    riskLevel: 'low',
    aliases: ['Isomalt', 'E 953'],
  },
  {
    eNumber: 'E954',
    name: 'Saccharin',
    functionClass: 'Süßungsmittel',
    riskLevel: 'medium',
    aliases: ['Saccharin', 'Sacharin', 'E 954'],
  },
  {
    eNumber: 'E955',
    name: 'Sucralose',
    functionClass: 'Süßungsmittel',
    riskLevel: 'low',
    aliases: ['Sucralose', 'E 955'],
  },
  {
    eNumber: 'E957',
    name: 'Thaumatin',
    functionClass: 'Süßungsmittel',
    riskLevel: 'none',
    aliases: ['Thaumatin', 'E 957'],
  },
  {
    eNumber: 'E959',
    name: 'Neohesperidin DC',
    functionClass: 'Süßungsmittel',
    riskLevel: 'low',
    aliases: ['Neohesperidin', 'E 959'],
  },
  {
    eNumber: 'E960',
    name: 'Steviolglycoside',
    functionClass: 'Süßungsmittel',
    riskLevel: 'none',
    aliases: ['Steviolglycoside', 'Stevia', 'Steviolglykoside', 'E 960'],
  },
  {
    eNumber: 'E961',
    name: 'Neotam',
    functionClass: 'Süßungsmittel',
    riskLevel: 'low',
    aliases: ['Neotam', 'E 961'],
  },
  {
    eNumber: 'E962',
    name: 'Aspartam-Acesulfam-Salz',
    functionClass: 'Süßungsmittel',
    riskLevel: 'medium',
    aliases: ['Aspartam-Acesulfam', 'E 962'],
  },
  {
    eNumber: 'E965',
    name: 'Maltit',
    functionClass: 'Süßungsmittel',
    riskLevel: 'low',
    aliases: ['Maltit', 'Maltitol', 'E 965'],
  },
  {
    eNumber: 'E967',
    name: 'Xylit',
    functionClass: 'Süßungsmittel',
    riskLevel: 'none',
    aliases: ['Xylit', 'Xylitol', 'Birkenzucker', 'E 967'],
  },
  {
    eNumber: 'E968',
    name: 'Erythrit',
    functionClass: 'Süßungsmittel',
    riskLevel: 'none',
    aliases: ['Erythrit', 'Erythritol', 'E 968'],
  },

  // ===== Sonstige (Other notable additives) =====
  {
    eNumber: 'E503',
    name: 'Ammoniumcarbonat',
    functionClass: 'Backtriebmittel',
    riskLevel: 'low',
    aliases: ['Ammoniumcarbonat', 'Hirschhornsalz', 'E 503'],
  },
  {
    eNumber: 'E551',
    name: 'Siliciumdioxid',
    functionClass: 'Trennmittel',
    riskLevel: 'low',
    aliases: ['Siliciumdioxid', 'Siliziumdioxid', 'Kieselsäure', 'E 551'],
  },
  {
    eNumber: 'E553b',
    name: 'Talkum',
    functionClass: 'Trennmittel',
    riskLevel: 'low',
    aliases: ['Talkum', 'E 553b'],
  },
  {
    eNumber: 'E554',
    name: 'Natriumaluminiumsilicat',
    functionClass: 'Trennmittel',
    riskLevel: 'medium',
    aliases: ['Natriumaluminiumsilicat', 'E 554'],
  },
  {
    eNumber: 'E579',
    name: 'Eisengluconat',
    functionClass: 'Stabilisator',
    riskLevel: 'none',
    aliases: ['Eisengluconat', 'E 579'],
  },
  {
    eNumber: 'E620',
    name: 'Glutaminsäure',
    functionClass: 'Geschmacksverstärker',
    riskLevel: 'low',
    aliases: ['Glutaminsäure', 'E 620'],
  },
  {
    eNumber: 'E900',
    name: 'Dimethylpolysiloxan',
    functionClass: 'Schaumverhüter',
    riskLevel: 'low',
    aliases: ['Dimethylpolysiloxan', 'E 900'],
  },
  {
    eNumber: 'E901',
    name: 'Bienenwachs',
    functionClass: 'Überzugsmittel',
    riskLevel: 'none',
    aliases: ['Bienenwachs', 'E 901'],
  },
  {
    eNumber: 'E903',
    name: 'Carnaubawachs',
    functionClass: 'Überzugsmittel',
    riskLevel: 'none',
    aliases: ['Carnaubawachs', 'E 903'],
  },
  {
    eNumber: 'E904',
    name: 'Schellack',
    functionClass: 'Überzugsmittel',
    riskLevel: 'low',
    aliases: ['Schellack', 'E 904'],
  },
  {
    eNumber: 'E920',
    name: 'L-Cystein',
    functionClass: 'Mehlbehandlungsmittel',
    riskLevel: 'low',
    aliases: ['L-Cystein', 'Cystein', 'E 920'],
  },
  {
    eNumber: 'E927b',
    name: 'Carbamid',
    functionClass: 'Mehlbehandlungsmittel',
    riskLevel: 'low',
    aliases: ['Carbamid', 'Harnstoff', 'E 927b'],
  },
  {
    eNumber: 'E938',
    name: 'Argon',
    functionClass: 'Treibgas',
    riskLevel: 'none',
    aliases: ['Argon', 'E 938'],
  },
  {
    eNumber: 'E941',
    name: 'Stickstoff',
    functionClass: 'Treibgas',
    riskLevel: 'none',
    aliases: ['Stickstoff', 'E 941'],
  },
  {
    eNumber: 'E948',
    name: 'Sauerstoff',
    functionClass: 'Treibgas',
    riskLevel: 'none',
    aliases: ['Sauerstoff', 'E 948'],
  },
  {
    eNumber: 'E999',
    name: 'Quillajaextrakt',
    functionClass: 'Schaumverhüter',
    riskLevel: 'low',
    aliases: ['Quillajaextrakt', 'E 999'],
  },

  // ===== Zuckeraustauschstoffe =====
  {
    eNumber: 'E1200',
    name: 'Polydextrose',
    functionClass: 'Füllstoff',
    riskLevel: 'low',
    aliases: ['Polydextrose', 'E 1200'],
  },
  {
    eNumber: 'E1404',
    name: 'Oxidierte Stärke',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Oxidierte Stärke', 'E 1404'],
  },
  {
    eNumber: 'E1412',
    name: 'Dinatriumphosphatstärke',
    functionClass: 'Stabilisator',
    riskLevel: 'low',
    aliases: ['Dinatriumphosphatstärke', 'E 1412'],
  },
  {
    eNumber: 'E1414',
    name: 'Acetyliertes Distärkephosphat',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Distärkephosphat', 'E 1414'],
  },
  {
    eNumber: 'E1422',
    name: 'Acetyliertes Distärkeadipat',
    functionClass: 'Verdickungsmittel',
    riskLevel: 'low',
    aliases: ['Distärkeadipat', 'E 1422'],
  },
  {
    eNumber: 'E1442',
    name: 'Hydroxypropyldistärkephosphat',
    functionClass: 'Stabilisator',
    riskLevel: 'low',
    aliases: ['Hydroxypropyldistärkephosphat', 'E 1442'],
  },
  {
    eNumber: 'E1450',
    name: 'Stärkeoctenylsuccinat',
    functionClass: 'Stabilisator',
    riskLevel: 'low',
    aliases: ['Stärkeoctenylsuccinat', 'E 1450'],
  },
  {
    eNumber: 'E1520',
    name: 'Propylenglycol',
    functionClass: 'Feuchthaltemittel',
    riskLevel: 'low',
    aliases: ['Propylenglycol', 'Propylenglykol', 'E 1520'],
  },
];
